# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(507, 524)
        font = QtGui.QFont()
        font.setPointSize(12)
        Form.setFont(font)
        self.twStuffs = QtWidgets.QTableWidget(Form)
        self.twStuffs.setGeometry(QtCore.QRect(10, 330, 491, 192))
        self.twStuffs.setObjectName("twStuffs")
        self.twStuffs.setColumnCount(0)
        self.twStuffs.setRowCount(0)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 362))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.linefio = QtWidgets.QLineEdit(self.layoutWidget)
        self.linefio.setObjectName("linefio")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.linefio)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.rbwoman = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbwoman.setObjectName("rbwoman")
        self.horizontalLayout.addWidget(self.rbwoman)
        self.rdman = QtWidgets.QRadioButton(self.layoutWidget)
        self.rdman.setObjectName("rdman")
        self.horizontalLayout.addWidget(self.rdman)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.speg = QtWidgets.QSpinBox(self.layoutWidget)
        self.speg.setObjectName("speg")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.speg)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lephone = QtWidgets.QLineEdit(self.layoutWidget)
        self.lephone.setObjectName("lephone")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lephone)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.leEmail = QtWidgets.QLineEdit(self.layoutWidget)
        self.leEmail.setObjectName("leEmail")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.leEmail)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.cbpost = QtWidgets.QComboBox(self.layoutWidget)
        self.cbpost.setObjectName("cbpost")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.cbpost)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.spexp = QtWidgets.QSpinBox(self.layoutWidget)
        self.spexp.setObjectName("spexp")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.spexp)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(360, 10, 101, 95))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pnopen = QtWidgets.QPushButton(self.layoutWidget1)
        self.pnopen.setObjectName("pnopen")
        self.verticalLayout.addWidget(self.pnopen)
        self.pbin = QtWidgets.QPushButton(self.layoutWidget1)
        self.pbin.setObjectName("pbin")
        self.verticalLayout.addWidget(self.pbin)
        self.pbdel = QtWidgets.QPushButton(self.layoutWidget1)
        self.pbdel.setObjectName("pbdel")
        self.verticalLayout.addWidget(self.pbdel)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Cotrydniki"))
        self.label.setText(_translate("Form", "ФИО"))
        self.rbwoman.setText(_translate("Form", "женский"))
        self.rdman.setText(_translate("Form", "мужской"))
        self.label_2.setText(_translate("Form", "Пол"))
        self.label_3.setText(_translate("Form", "Возраст"))
        self.label_4.setText(_translate("Form", "Телефон"))
        self.label_5.setText(_translate("Form", "E-mail"))
        self.label_6.setText(_translate("Form", "Должность"))
        self.label_7.setText(_translate("Form", "Стаж"))
        self.pnopen.setText(_translate("Form", "Открыть"))
        self.pbin.setText(_translate("Form", "Добавить"))
        self.pbdel.setText(_translate("Form", "Удалить"))
